### ISSUE TITLE
Please add Carthage support

### ISSUE THREAD

**Issue by hansflug** [usebutton/ios-deeplink-sdk#10]
Please add Carthage support to your open source.
see [Carthage/](https://github.com/Carthage/Carthage)

**Comment by wessmith** [comment]
I've never used Carthage. At quick glance at the documentation, it doesn't look like there's anything to do to support it–which sounds like the main goal. 

If you know of work that needs to be done, you're more than welcome to submit a pull request that adds support and we'll check it out.

**Comment by chrismaddern** [comment]
Let's leave this issue open to track it until we get a chance to try it out. As @wessmith mentioned it should 'just work' but if there are basic build changes we can make, we'll take a look :)

**Comment by chrismaddern** [comment]
Closing for now.

We would definitely welcome a P/R that adds support without diminishing CocoaPods functionality, but are not going to undertake the work at this time.
