### ISSUE TITLE
first path component stripped out

### ISSUE THREAD

**Issue by Dillion** [usebutton/ios-deeplink-sdk#12]
it seems that the first path component is stripped out in the route matcher, which is not what I would expect

i.e. given a route declared as 

<pre><code> self.router[@"routeA/:param1/:param2/:param3"] = ^(DPLDeepLink *link) {
    };
</code></pre>

I would expect a URL in the form <pre><code>scheme://routeA/param1/param2/param3</code></pre> to match, but it matches only if there is an additional path component after the scheme, e.g. <pre><code>scheme://x/routeA/param1/param2/param3</code></pre>.

Using v0.1.1 from cocoapods

**Comment by wessmith** [comment]
That first item in the URL is actually the host of the URL not part of the path. For example: `scheme://host/path/to/something`.  We're not matching on host yet (see #9).

Sorry for the confusion.
