### ISSUE TITLE
Should we use didFinishLaunch to handle app URL or openUrl is enough?

### ISSUE THREAD

**Issue by Just-** [usebutton/ios-deeplink-sdk#3]
Just a question to understand

According apple documentation we don't need to handle URL in both places `openUrl` and `didFinishLaunch`. Have you any trouble if using only `openUrl`? Don't you have duplicated reaction if using both?

> Your implementation of this method should open the specified URL and update its user interface accordingly. If your app had to be launched to open the URL, the app calls the application:willFinishLaunchingWithOptions: and application:didFinishLaunchingWithOptions: methods first, followed by this method. The return values of those methods can be used to prevent this method from being called. (If the app is already running, only this method is called.)

https://developer.apple.com/library/ios/documentation/UIKit/Reference/UIApplicationDelegate_Protocol/index.html#//apple_ref/occ/intfm/UIApplicationDelegate/application:openURL:sourceApplication:annotation:

**Comment by wessmith** [comment]
Thanks for pointing this out. I just tested it and it does in fact work as documented.

**Comment by wessmith** [comment]
This is corrected in `0.1.1`. Thanks!

**Comment by Just-** [comment]
Great!
